export {default as Navbar} from "./Navbar"
export {default as HomePage} from "./HomePage"
export {default as News} from "./News"
export {default as Tech} from "./Tech"
export {default as CryptoDetails} from "./CryptoDetails"
export {default as LocalNews} from "./LocalNews"
export {default as WeatherUpdates} from "./WeatherUpdates"
